import { Command } from 'commander';
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { logger } from '../utils/logger.js';
import { askInput } from '../utils/prompt.js';

export function registerCode(program: Command): void {
  program
    .command('code')
    .description('Generate code from a prompt')
    .argument('[prompt]', 'Description of code to generate')
    .option('-o, --output <path>', 'Output file path')
    .option('-l, --language <lang>', 'Programming language')
    .action(async (prompt, opts) => {
      const desc = prompt || await askInput('Describe the code to generate');
      if (!desc) { logger.error('No prompt provided'); process.exit(1); }

      const ext = opts.language === 'python' ? '.py' : opts.language === 'rust' ? '.rs' : '.ts';
      const outputPath = opts.output ? resolve(opts.output) : resolve(`generated_${Date.now()}${ext}`);

      logger.info(`Generating: ${desc.slice(0, 60)}...`);
      logger.step(`Output: ${outputPath}`);

      const code = generatePlaceholder(desc, opts.language ?? 'typescript');

      const dir = dirname(outputPath);
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
      writeFileSync(outputPath, code, 'utf-8');
      logger.success(`Generated ${outputPath}`);
    });
}

function generatePlaceholder(description: string, lang: string): string {
  const comment = lang === 'python' ? '# ' : lang === 'html' ? '<!-- ' : '// ';
  const close = lang === 'html' ? ' -->' : '';
  return `${comment} Generated by OpenIO${close}
${comment} ${description}${close}
${comment} ${new Date().toISOString()}${close}

`;
}
