import { Command } from 'commander';
import { resolve } from 'node:path';
import { logger } from '../utils/logger.js';
import { ProjectAnalyzer, ProjectPlanner, ProjectGenerator, ProjectMigrator, DependencyAnalyzer } from '@openio/project-engine';
import { askSelect, askInput } from '../utils/prompt.js';

export function registerProject(program: Command): void {
  program
    .command('project')
    .description('Project analysis and scaffolding')
    .argument('[action]', 'Action: analyze, scaffold, migrate, deps')
    .option('-d, --dir <path>', 'Project directory', '.')
    .option('-t, --template <name>', 'Template name (nextjs, react, express, fastapi)')
    .option('-n, --name <name>', 'Project name')
    .option('--from <framework>', 'Migrate from framework')
    .option('--to <framework>', 'Migrate to framework')
    .action(async (action, opts) => {
      const dir = resolve(opts.dir);
      const analyzer = new ProjectAnalyzer(dir);

      if (!action) {
        logger.info('Use: openio project analyze|scaffold|migrate|deps [options]');
        return;
      }

      if (action === 'analyze') {
        const info = await analyzer.analyze();
        logger.info(`Project: ${info.name}`);
        console.log(`  Language:        ${info.language}`);
        console.log(`  Package manager: ${info.packageManager}`);
        console.log(`  Frameworks:      ${info.frameworks.join(', ') || 'none'}`);
        console.log(`  Entry points:    ${info.entryPoints.join(', ') || 'none'}`);
        console.log(`  Files:           ${info.fileCount}`);
        console.log(`  Dirs:            ${info.dirCount}`);
        console.log(`  Dependencies:    ${Object.keys(info.dependencies).length}`);
        return;
      }

      if (action === 'scaffold') {
        const template = opts.template ?? await askSelect('Template', [
          { name: 'Next.js', value: 'nextjs' },
          { name: 'React (Vite)', value: 'react' },
          { name: 'Express API', value: 'express' },
          { name: 'FastAPI', value: 'fastapi' },
        ]);
        const name = opts.name ?? await askInput('Project name', { default: 'my-app' });
        const gen = new ProjectGenerator(dir);
        const files = await gen.generate(template, { projectName: name, description: `${name} - generated by OpenIO` });
        logger.success(`Created ${files.length} files in ${dir}`);
        return;
      }

      if (action === 'migrate') {
        if (!opts.from || !opts.to) {
          logger.error('Use --from <framework> and --to <framework>');
          return;
        }
        const migrator = new ProjectMigrator(dir);
        const plan = await migrator.analyzeMigration(opts.from, opts.to);
        logger.info(`Migration plan: ${opts.from} → ${opts.to}`);
        for (const step of plan.steps) {
          console.log(`  ${step.automated ? '✓' : '○'} ${step.title}`);
        }
        return;
      }

      if (action === 'deps') {
        const deps = new DependencyAnalyzer(dir);
        const graph = await deps.buildGraph();
        logger.info(`Dependency graph: ${graph.nodes.length} nodes, ${graph.edges.length} edges`);
        if (graph.cycles.length > 0) {
          logger.warn(`${graph.cycles.length} circular dependenc${graph.cycles.length === 1 ? 'y' : 'ies'} detected:`);
          for (const cycle of graph.cycles) {
            console.log(`  ${cycle.join(' → ')}`);
          }
        } else {
          logger.success('No circular dependencies');
        }
        return;
      }

      logger.error(`Unknown action: ${action}`);
    });
}
